[package]
name = "iv"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30"
softbuffer = "0.4"
image = "0.25"
clap = { version = "4", features = ["derive"] }
sysinfo = "0.31"
log = "0.4"
env_logger = "0.11"
image_hasher = "3.1.0"
rayon = "1.11.0"
